language: java
jdk:
  - openjdk8

before_install:
  - chmod +x mvnw

branches:
  only:
    - develop

cache:
  directories:
    - '$HOME/.m2/repository'

script: "./mvnw clean package"

notifications:
  email:
    recipients:
      - hscom96@gmail.com 
