language: java
jdk:
  - openjdk8

before_install:
  - chmod +x mvnw

branches:
  only:
    - develop

cache:
  directories:
    - '$HOME/.m2/repository'

script: "./mvnw clean package"

notifications:
  slack: auctionnara:bbI6hEve7YM2YlHDKpBbwE6m
