server:
  port: 8000

zuul:
  ignoredServices: '*'
  prefix:
  routes:
    item:
      path: /api/item/**
      serviceId: platform
      stripPrefix: false
    category:
      path: /api/category/**
      serviceId: platform
      stripPrefix: false
    review:
      path: /api/review/**
      serviceId: platform
      stripPrefix: false
    bid:
      path: /api/bid/**
      serviceId: platform
      stripPrefix: false
    member:
      path: /api/member/**
      serviceId: platform
      stripPrefix: false
    store:
      path: /api/store/**
      serviceId: platform
      stripPrefix: false
    order:
      path: /api/order/**
      serviceId: platform
      stripPrefix: false


endpoints:
  routes:
    sensitive: false
  trace:
    sensitive: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

#jwt
jwt:
  secret: govlepel@$&amp