server:
  port: 8000

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    item:
      path: /item/**
      serviceId: platform
      strip-prefix: false
    random:
      path: /random/**
      serviceId: platform
      strip-prefix: false


endpoints:
  routes:
    sensitive: false
  trace:
    sensitive: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/