language: java
jdk:
  - openjdk8

branches:
  only:
    - develop

cache:
  directories:
    - '$HOME/.m2/repository'

script: "./mvnw clean package"

before_install:
  - chmod +x mvnw

before_deploy:
  - zip -r springboot-boltauction *
  - mkdir -p deploy
  - mv springboot-boltauction.zip deploy/springboot-boltauction.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: boltauction # 6-3-3에서 생성한 S3 버킷
    region: us-east-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: bolt-auction/bolt-auction-backend #Github 주소
      branch: develop

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: boltauction # S3 버킷
    key: springboot-boltauction.zip
    bundle_type: zip
    application: boltauction # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: boltauction  # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: us-east-2
    wait-until-deployed: true
    on:
      repo: bolt-auction/bolt-auction-backend
      branch: develop

notifications:
  slack: auctionnara:bbI6hEve7YM2YlHDKpBbwE6m
