spring:
  #jwt
  jwt:
    secret: govlepel@$&amp
  main:
    banner-mode: 'off'
  #Redis specific configurations
  redis:
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379


# Security log level Setting
logging:
  level:
    org:
      hibernate: info
      springframework:
        security: debug

rabbitmq:
  relay:
    port: 61613

#rest template Connection Pool
rest:
  connPool:
    MaxConnPerRoute: 20
    MaxConnTotal: 50
  factory:
    setConnectTimeout: 2000
    setReadTimeout: 5000

#Service discovery Setting
eureka:
  client:
    service-url:
      default: http://${base.addr}:8761/eureka/

#actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

## RabbitMQ 설정
platform:
  queue: platform_communication_queue
  exchange: platform_exchange
  notify:
    key: platform.notify
  anything:
    routing-key: platform.*

lombok:
  anyConstructor:
    addConstructorProperties: true